FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY RpaWorker/RpaWorker.csproj RpaWorker/
WORKDIR /src/RpaWorker

RUN dotnet restore

COPY RpaWorker/. ./

RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "RpaWorker.dll"]