FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY RpaApi/RpaApi.csproj RpaApi/
COPY RpaWorker/RpaWorker.csproj RpaWorker/

WORKDIR /src
RUN dotnet restore RpaApi/RpaApi.csproj

COPY RpaApi/. RpaApi/
COPY RpaWorker/. RpaWorker/

WORKDIR /src/RpaApi
RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "RpaApi.dll"]